before_script:
    - ruby -v
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update -qy
    - apt-get install -y libssl-dev build-essential wget ruby-dev heroku-toolbelt
    - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.6/install.sh | bash
    - source /root/.bashrc
    - nvm install 6.6.0
    - nvm use 6.6.0
    - node -v
    - npm -v
    - gem install dpl
    - npm install -g rollup
    - cd bicycleparking && npm install && npm run build && cd ..

services:
  - postgres:latest

variables:
  POSTGRES_DB: bike_parking_toronto
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - python manage.py test

staging:
  type: deploy
  script:
  - dpl --provider=heroku --app=torontobikeparking-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  type: deploy
  script:
  - dpl --provider=heroku --app=torontobikeparking --api-key=$HEROKU_STAGING_API_KEY
  only:
  - tags
