services:
  - postgres:latest

variables:
  POSTGRES_DB: bike_parking_toronto
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

test:
  script:
  # this configures Django application to use attached postgres database that is run on `postgres` host
  - apt-get update -qy
  - apt-get install -y python-dev python-pip
  - pip install -r requirements.txt
  - python manage.py test

staging:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install curl
  - curl -sL https://deb.nodesource.com/setup_6.x | bash
  - apt-get install -y -qq ruby-dev nodejs npm
  - ln -s /usr/bin/nodejs /usr/bin/node
  - node -v && npm -v
  - gem install dpl
  - cd bicycleparking && npm install && npm run build
  - cd .. && dpl --provider=heroku --app=torontobikeparking-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  type: deploy
  script:
  - apt-get update -qy
  - apt-get install -y ruby-dev && nodejs
  - gem install dpl
  - cd bicycleparking && npm install && npm run build
  - cd .. && dpl --provider=heroku --app=torontobikeparking --api-key=$HEROKU_PRODUCTION_API_KEY
  only:
  - tags
