before_script:
    - ruby -v
    - echo "deb http://toolbelt.heroku.com/ubuntu ./" > /etc/apt/sources.list.d/heroku.list
    - wget -O- https://toolbelt.heroku.com/apt/release.key | apt-key add -
    - apt-get update -qy
    - apt-get install -y libssl-dev build-essential wget ruby-dev heroku-toolbelt
    - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
    - source /root/.bashrc
    - nvm install --lts
    - nvm use node
    - node -v
    - npm -v
    - gem install dpl
    - cd bicycleparking && npm install && npm run build && cd ..

services:
  - name: mdillon/postgis
    alias: postgis

variables:
  POSTGRES_DB: bike_parking_toronto
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
test:
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-pip
  - pip3 install -r requirements.txt
  - source test/useci
  - python3 manage.py test --no-input

staging:
  type: deploy
  script:
  - dpl --provider=heroku --app=torontobikeparking-staging --api-key=$HEROKU_STAGING_API_KEY
  only:
  - master

production:
  type: deploy
  script:
  - dpl --provider=elasticbeanstalk --access-key-id=$AWS_ACCESS_KEY_ID --secret-access-key="$AWS_SECRET_ACCESS_KEY" --app="bikespace" --env="bikespace-env" --region="us-east-1"
  only:
  - tags
