version: '3.6'

services:
    db:
        image: cityofedmonton/bikespace-db
        build:
            context: ./db
            dockerfile: Dockerfile
        ports:
            - 5432:5432
    web:
        image: cityofedmonton/bikespace-web
        build: .
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment: 
            - BIKE_DB_HOST=db
            - GOOGLE_APPLICATION_CREDENTIALS=/code/service-account.json