# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-26 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bicycleparking', '0013_remove_picture_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyanswer',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='bicycleparking.Picture'),
        ),
    ]
